### ISSUE TITLE
WindowGetterPlugin在获取某些属性时会报错

### ISSUE THREAD

**Issue by dengBox** [jardenliu/wujie-polyfill#2]
如图会报错:
<img width="797" alt="5A9C8DB3-ADB9-4095-8DCF-98460F593911" src="https://github.com/jardenliu/wujie-polyfill/assets/29906246/295f8502-5c99-4ae6-ad39-d9c622662e2b">
目前发现会报错的属性有：
1.  `Symbol(Symbol.toStringTag)`
<img width="688" alt="image" src="https://github.com/jardenliu/wujie-polyfill/assets/29906246/60494382-7fcd-460a-a46a-b94d3c1e10b3">

**Comment by jardenliu** [comment]
fix: b12cb8626a70fca9ab630b03ebf552fa8fe87c44

**Comment by jardenliu** [comment]
升级到1.0.4
