### ISSUE TITLE
【EventTargetPlugin】插件存在问题

### ISSUE THREAD

**Issue by ShihHsing** [jardenliu/wujie-polyfill#4]
基座与子项目都是vue2，预加载、预执行的子应用event.target并未被修改
![image](https://github.com/jardenliu/wujie-polyfill/assets/18413105/740f69d8-627f-46d3-8daa-1c5b6874fab7)

**Comment by jardenliu** [comment]
有复现demo吗

**Comment by zzj-user** [comment]
![image](https://github.com/jardenliu/wujie-polyfill/assets/71804264/4e7e68e6-afb7-4f10-8480-3126d16d31f9)
此处的Event.prototype为什么不是对子应用的event做修改? 此逻辑只会在第一个激活的应用中生效
