### ISSUE TITLE
子应用x-spreadsheet Excel库，mousemove事件触发时的offsetY计算有问题

### ISSUE THREAD

**Issue by xult2471** [jardenliu/wujie-polyfill#8]
在子应用中用了x-spreadsheet Excel库中，在mousemove事件触发时event.offsetY计算有问题，应该是基于event.target计算坐标的，但是结果还是基于wujie-app，什么时候能修复下啊？急
![image](https://github.com/jardenliu/wujie-polyfill/assets/20784068/7d11ff96-0d35-4826-9204-9c458147c6ad)

**Comment by jardenliu** [comment]
没时间弄
